# ===============postgresql配置========================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.200.112:5432/suphowe?useSSL=false
    username: root
    password: root
# ===============mybatis配置========================
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml